:PROPERTIES:
:ID:       d0df3b6c-f23e-4dae-bb25-4f72e194bd82
:END:
#+title: Nov-2020
#+ROAM_TAGS: Volcabulary

- tag :: [[file:20201027222847-volcabulary.org][Volcabulary]] 

* conform
iPhone's design conform to the principle of simplicity.

* impregnate

* arrest warrant

* incest, adultery

* inalienable
Unlike money and relationship, knowledge and experience are the only inalienable part of a human.

* reconcile
It is sometimes difficult to reconcile science and religion.

* espouse

I do not espouse unsafe sex.

* tribe

a tribe is a human social group.

* contradiction

* tyranny

* in the parlance of our time
the phrases, words using in today's language

* caveat

* disjointed
When people lie, their statements are disjointed.

* moronic

* deception

The companys are guilty of deception if they exaggerate the functions of their products.

* conservative

In a conservative opinion, women are supposed to get married and give birth.

* contraceptive (tool)

Condom is a type of contraceptive.

* contraception (method)

* inflammatory

I was inflammatory everytime I saw the name Xiao Zhan on the top search of weibo.

* forgo

Almost no one will forgo an opportunity to date Aragaki Yui.

* surge

I felt depression surging inside me when my ex broke up with me.

* resent

I resented being told to do things I don't like.

