:PROPERTIES:
:ID:       b0c7f521-d5ec-4341-8e01-8c8ffe5e19b5
:END:
#+title: Marcus Aurelius' Quotes

When you arise in the morning, think of what a privilege it is to be alive, to think, to enjoy, to love.

The happiness of your life depends upon the quality of your thoughts.

Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.

Waste no more time arguing about what a good man should be. Be one.

If you are distressed by anything external, the pain is not due to the thing itself but to your estimate of it and this you have the power to revoke at any moment.

It it not death that a man should fear but he should fear never beginning to live.

Very little is needed to make a happy life, it is all within yourself in your way of thinking.

Reject your sense of injury and the injury itself disappears.

Do not act as if your were going to live ten thousand years. Death hangs over you. While you live, while it is in your power, be good.

Here is a rule to remember in future, when anything tempts you to feel bitter: not "This is misfortune" but "To bear this worthily is good fortune".

How much time he gains who does not look to see what his neighbour says or does or thinks, but only at what he does himself, to make it just and holy.

Do every act of your life as though it were the very last act of your life.
