:PROPERTIES:
:ID:       b1a39989-9813-4746-9e57-022b33af6981
:END:
#+title: Parenting
#+ROAM_TAGS: Thesis

* Parenting styles

  Two primary factors to determine parenting style are parental responsiveness and parental demandingness. 
Parental responsiveness refers to the degree parents respond to the child's needs.

  It has been hypothesized that the relation between parenting styles and academic achievement is mediated by students' motivation.

** proactive behavioral control

   higher responsiveness is associated with learning goal orientation.

   promotes goal-directed behavioral and reduces externalizing problem, such as truancy.

** reative behavioral control (harsh, punishment)

   violate the principle of autonomy support from SDT.

** psychological control (guilt induction, shaming)

** overcontrol v.s. autonomy granting

** shadow education
   [[zotero://select/items/1_SH5QW7BL][Zhang, W. (2020) Shadow education in the service of tiger parenting: Strategies used by middle‐class families in China]]

* measures

  [[zotero://select/items/1_PALEIFKY][Roksa, J. & Potter, D. (2011) Parenting and Academic Achievement: Intergenerational Transmission of Educational Advantage]]

