:PROPERTIES:
:ID:       93e647d3-545b-4e16-ad1f-c4140736bac3
:END:
#+title: May-2021
#+ROAM_TAGS: Volcabulary

- tag :: [[file:20201027222847-volcabulary.org][Volcabulary]]
  
* overhalu
  
* bewhiskered

* enliven the argument

   The main character's death enlivens the story.

* invigorate

  Gary Vee's podcasts and posts on Instagram always invigorate me.

* peculiar stance

  Believing that men are genuinely doing better work than women in academia is a peculiar stance nowadays.

* compensate

  His enthusiasm compensates for his lack of experience.

* timid

  I was a timid guy before college.

* irresolute

  Zhang Wu Ji is the most irresolute character in Jin Yong's novels.

* undisguised

  disguise

* blunder

  Side effect is not a blunder in programming.

* habitual

  He is a habitual thief.

  I used to pick up my phone habitually.

* forcible
  
  forcible entry

* transitive

  transitive verb

* perfunctory

  I always make perfunctory greetings to my relatives that I don't know.
  
* vigor  

  vigor and enthusiasm

* commendatory term / derogatory term  

* tame

After a few months' training, my dog has become tame.

* evoke

** evoke images and sensations

* commensurate

  If the clergy had privileges, they also had commensurate duties.
  
* terrific
  you look terrific
  
* mutter

* epigram

* eyesore

* stationary
 
* buoy
  buoy up

* ripple

* flutter

* rear
  rear window

* paralyzed

* witty

* surname (family name)

* imperceptibly

* fright

* totter
  the object she was balancing had obviously *tottered* a little and given her something of a fright.
  
* slender
  
* suntan
  
* porch

* lid
  jar lid, laptop lid

* quarter
  
* ludicrous
  
* ramble

* prelude

* in one's place
  Encouraged by his wife, Macbeth achieved his ambition and realized the prediction of the witches by murdering Duncan and becoming king of Scotland *in his place*.

* empire emperor

* debilitate

* err

* antecedent

* stiff

* viable

* converse
  converse with

* single out

* heritage

* accusingly

* unobtrusively

* blend

* impersonal

* bantering

* sheer

* confess

* corky

* claret

* wink

* ferociously

* fervent sun

* Nordics

* butler

* affection

* glowing
  glowing face

* compel

* desert
  run away

* lingering

* extemporize

* napkin

* devoid

* gaiety

* lawn

* stable
  
* settee

* cynical

* defiant

* sophisticated

* assert

* crimson
  crimson room

* bloom

* uninflected

* soothing

* remark

* contemptuous

* rotogravure

* veranda

* libel

* dock

* hastily

* in exchange for

I spend most of my time studying in exchange for the knowledge.

* accuse

* sweep

* metropolitan
  Shen Zhen is a metropolitan city of the Grang Dong province. 

* monolithic

* preliminary
  preliminary results
  preliminary findings

* social stratification

* preserve

* premise 

* purposive

* comprise

* grant

* incur

  incur failure
  incur debts

* so much as
  but rather
  
  I don't think it's love so much as lust.

* patriotic

* compatriot

* exquisite

* passenger

* rebuke

* shift

* confine

* monitor

* crisp

  crisp apple
  crisp cookie

* narcissistic

* impotence

* orgasm

* relapse

* unrelenting 

* encore

* conspiracy

* keep expectation in check

* syringe

* pledge

  Xi Jinping, China's top leader, *has pledged to* make a Covid-19 vaccine a "global public good."

* generous

  noun generosity

* subsume

  They don't want to subsume their generosity in their products under the U.N. brand.

* backfire

  My plans to study computer science backfired on me when there was not enough time to finish my thesis.

* begrude

  We don't begrude you that special endowment.

* revolt

  Her cliams to the ownership to the tree revolts the others.

* cache

* mattress

* doctrine

* upbringing

* resemble

  This proposal differs from the last one in many important respects.

* intense 

  intense belief

* induce

  Nothing can induce me to take drugs.

* autonomous

* introjected

* continuum

* postulate

* refinement

* omnivorous

* engross

  Programming engrosses me.
  
* secede

* confederacy

* tweak

  It's common in computer programming to tweak an exsiting program instead of writing a new program from scratch.

* tinker

  It's a waste of time tinkering around different operatings systems.

* protagonist

* inarguration

* narrative

