:PROPERTIES:
:ID:       8153bde0-81b3-4ff0-a19a-3b17bb34b611
:END:
#+title: Oct-2021

* excruciating

* grinder

coffee grinder

* mantra

* seething

* midst

I'm in the midst of deep exhaustion.

* wobbly

verb: wobble

my legs wobbled after I finished the marathon.

* slack

  loose

* introspective

* vitality

* linger

* spare

extra

a spare key

* frugal

being frugal means spending money very carefully

a frugal lifestyle
a frugal meal of bread and soup

* peculiar

* remorseful

* gingerly

* drainage

They made some mistake in the drainage work on the veranda above us.

* crisp

The air is crisp

* lavishly

  The skyscrapers lavishly reflect the sun's rays.

* toe straps

* stiff

My leg muscles are stiff.

* accountrement (equipment)

* nimble

nimble person
nimble mind

* forte

Bicycle is definitely not my forte.

* torrential

  torrential rain
  a torrential storm

* strap

I strap on my helmet.

* stremlined

a stremlined helmet.

* invigorate

A cut in tax will invigorate economy.

* buzzword

* allusion

  Lu Xun's articles are full of allusions to the China's society.

* covert

* sensation

The strange sensation I'd had on the inside of my knee had vanished.

* cash in one's chip

go to bed; have a rest

* faint hope

* meticulous planning

* abstruse

* muscles cramp

* buoyant

* condemn

* obscenity

* curate
