:PROPERTIES:
:ID:       0516eece-32bf-40f2-a3f4-11bfd7b8c660
:END:
#+title: August-2021
#+filetags: :Volcabulary:

* anonymous

* precocious

* scam

* market cap (market capitalization)

* thought through

* metric

* scarcity

a scarcity of skilled workers slowed down the efficiency of production.

* melodramatic

* diversify

* incentive
  
  incentify

* engross

- something is so interesting that it gets all your attention.

that video game engrossed me, so I spend two weeks playing it.

I am so engrossed in programming.

* immerse

She wanted to improved her Japanese, so she immersed herself in Japanese animes for half a year.

* a guide to something

A normie's guide to using unix.

* trait

- a particular characteristic

specific traits of bitcoin

* self-propelling

* spit

* disclose

You can disclose your bitcoin wallet's address to your friends so that the can pay you or vice versa.

* merchant

* wary

  the nature of intimate relationship is being wary of the love of your lover.

* dispute

* mint

* tangible

  - not imaginary

