#+title: Jan-2021

* arena
  - Hearthstone arena
  - An sports arena

* stakeholder

The ceo is an employee and also a stakeholder of the company.

* altruistic

In China, every one knows Lei Feng is altruistic.

* spiteful

Tom is a spiteful boy, because he usually makes his parents upset.

* prophecy 

My prophecy for future computer is that it consists of a monitor and network module and it does not have hard disk and RAM, which means all the computing is done in the server it connected to.

* speculative

My decisions on investment is speculative.

* merit

Your code has merit.

* prevalent

TIK TOK is prevalent in both China and the US.

* volatile

My emotion was volatile after a break up.

* couch

Playing with your phones while lying on a couch hurts your back.

* recline

I enjoy reclining on the couch.

* idle

idle chat

* forthright

In China culture, forthright manner is sometimes considered rude.

His forthright manner can be mistaken rudeness.

* prudent

You should be prudent to avoid type mismatch while writing code. 

* refute

The only way to refute people's judgement is to be successful. 

* throughput

* metric

* elapse

4 years had elapsed since he left college and still he hadn't found a job.

* unwieldy

TV is an unwieldy item in my room.

* dissipation

Heat dissipation is an important metric when buying a new gaming PC.

* lucrative job

A type job with high income

* canonical

SICP is a canonical book for programmers to study.

* punctuality

I have procrastination. It makes me not punctual.

* obsessive
  
I am obsessive about computer science.

* compulsive

* composite

English is a composite of several languages like French, Latin and German.

* traversal

* ascertain
  ascertain turth

* conjecture

* pivot

* palette

* set aside

  set aside time to study what you want to.

* kick back (informal)

* binge

  binge on netflix

  binge-watch TV shows

  The Big Bang Theory is a bingeable TV shows.

* postpone

  I postponed my graduation for one year.
