#+title: Feb-2021
#+ROAM_TAGS: Volcabulary

- tag :: [[file:20201027222847-volcabulary.org][Volcabulary]] 

* shallow

  When implementing priority trees, we want to keep the binary tree shallow.

* get something out of the way

  get that out of the way really fast, and study a little bit.

* atheist

* conceive (of)

  No matter how old I am, my parents conceive of me as a kid.

* prologue

* soar

* whip
  
  the wind whips my hair.

  - whipped
  - whipping

* auxiliary

* kickoff

  kickoff(start) whatever course i am taking

* commute

  After 4, i will commute over our gym.

* clobber

* base off

  Our research is base off of the work done by our predecessor.

* sleeve

* dodger

  tax dodger

* voluntarily

* rusty

* famine

* premium

* pontificate

* cloth

  def: a piece of fabric

* wound

  if you get shot, you will have a gunshot wound.

* sabotage

  people's old identity can sabotage their new plans for change.

* sluggish

* obese

* prestige

* confine

* meditation

* friction

* ritual

* recurring

