#+title: Apr-2021
#+ROAM_TAGS: Volcabulary

- tag :: [[file:20201027222847-volcabulary.org][Volcabulary]] 

* batcha

* stripper

* appeal
  sex appeal
  lauch an appeal to raise money for victims
  the government have issued an appeal to the public to stay at home.
* famine
** def
   a situation in which there is not enough food for a great number of people.
** e.g
    The war caused widespread famine.

* entitlement

* suspicious
** e.g  
  Your competitor gave up the match without any reason. It was very suspicious.

* subjunctive

* mansion

* spawn

* spasm

* scab

* cognizant

* revamp

* saddle (with)
** def
  saddle A with B. == put B(a burdden, a problem) on A.
** e.g  
  Communism aided the West because it *saddle* an imperialist Russian state with an unworkable and unpopular economic system that could not keep up with its free-market competitors.

* quintessential
** e.g  
  Yum Cha is the quintessential Cantonese breakfast.

* peter out
** def
  gradually disappear

* anchorage

* clash (with)
** e.g
  My values clashes with my parents'.

* conciliatory

* embolden

* truculence

* maritime

* heedlessly

* consolidated

* shambolic

* invincibility

* dissent

* foment

* quash

* conscience

* deterrent

* regime

* deposition

** def
   a formal statement made or used in a law court

** e.g
   
* suit (lawsuit)
