#+title:  Apr-2021
#+ROAM_TAGS: Volcabulary

- tag :: [[file:20201027222847-volcabulary.org][Volcabulary]] 

* batch
** a group of things or people
** e.g
   You can buy a batch of eggs in supermarkets.

* stripper
** remover, performer that takes off his/her clothes

* appeal
  sex appeal
  lauch an appeal to raise money for victims
  the government have issued an appeal to the public to stay at home.

* famine
** a situation in which there is not enough food for a great number of people.
** e.g
    The war caused widespread famine.

* entitlement
** a feeling that you think you have the right to do something without any effort just because of who you are.
** e.g
   Many middle-class kids were born without any responsibility. Their parents do many things for them, which gives them a strong feeling of entitlement.

* suspicious
** e.g  
  Your competitor gave up the match without any reason. It was very suspicious.

* subjunctive
** grammar rule. a verb form that refers to actions that are possibilities rather than facts.

* mansion
** a very expensive house  
* spawn
  U
** the eggs of fish, frogs, etc.

* spasm
** an occasion when a muscle cannot be controlled
* scab
** a rough surface made of dried blood that forms over a cut or broken skin while it is healing

* cognizant
** realize
** e.g
   I am still tring to be cognizant of how to live my life.

* revamp
** to change something in order to improve it
** e.g   
   I have been using this PC for 3 years. It's quite slow nowadays, so it needs an revamp.

* saddle (with)
** saddle A with B. == put B(a burdden, a problem) on A.
** e.g  
  Communism aided the West because it *saddle* an imperialist Russian state with an unworkable and unpopular economic system that could not keep up with its free-market competitors.

* quintessential
** e.g  
  Yum Cha is the quintessential Cantonese breakfast.

* peter-out
** gradually disappear
** e.g
   Every romantic relationship peters out in the end.

* anchoraeg

* clash (with)
** e.g
  My values clashes with my parents'.

* conciliatory

* embolden

* truculence

* maritime

* heedlessly

* consolidated

* shambolic

* invincibility

* dissent

* foment

* quash

* conscience

* deterrent

* regime

* deposition

** def
   a formal statement made or used in a law court

** e.g
   
* suit (lawsuit)

* exert yourself

** def
   to work very hard and use a lot of physical and mental energy.

** e.g
   
   I didn't study hard last month. I need to exert myself to write my thesis in the next month.

* autonomy

* deteriorate

* life expectancy

* dissipate
** synonym
   peter out
** def
   gradually disappear
** e.g
  I dissipated my attention into different programming languages learning.

* transitory effect
  
* grudgingly

* paramount

* conceivable

* self-deception

* animosity

* retain

* wholesome

* docile

* ruthless

* deprive

* linger
  
* excessive

* intemperate

* rabble-rousing

* merit

* rebel against

* regress

* spectrum

  the specturm of related creeds that includes the feminist, gay rights, political corectiness, etc.

* -raiser
  
  money-raiser is a person who collect money for some reason.
  
* faint
* wear out
* run off
**  def
   run off x means leave x quickly
** e.g
   I will run off home after grad school because I haven't been at home for almost a year.

* condense
  
** def
   reduce

** e.g.
   I condensed his ten pages articles into two.

** adjective
   condensed soup

* projectile

* sheath
* submarine
* contrast
* vintage
* illuminate
* manicure
* hop on
* swear word
* whirring
* snap-up
* grabs
* surge
* relentless
* beckons
* soar
* grapple
* banquets
  a big banquet for weddings and family reunions
* splurge
* subsidize
* dampen
* appetite
* momentum
* mold
* olden
* cure your meat
* siren
* ramification
* ring ture
* intelligibly
* sluggish
* detriment
* hostility
* goofy
* aquatic
** living in water  


