:PROPERTIES:
:ID:       b5decbac-d1b9-4d3d-b430-4418241f4813
:END:
#+title: Oct-2022


* words

** melancholy

** insular

** heady

** nod to

refer to

** warhorse

** as loaded with fun as 

the movie is as loaded with fun as it is with social implications.

** evince

i've never evinced any desire to talk to my father.

** in extremis

** allegory

** fertilization and implantation

** masturbatory

** phantom

  phantom organization

** amputate

** scattered

scattered plot

my friends are scattered all over the world

** deter

nothing can deter my passion on learning computer science.

** equilibriumz

** insanity

insanity is doing the same thing, over and over again, but expecting different results.

** testimonials

** wrinkle

** butt in 
interupt

** conceivable
inconceivable

a world without books is inconceivable

** commence

commence coding

* sentences

** if you are having that kind of focused fun, there is a good chance the readers will too.

** it is better to be hated for what you are than to be loved for what you are not

** literature is a form of pleasure that i cannot derive from anything else.

