:PROPERTIES:
:ID:       4f1d56c0-9ee3-4eca-b7e0-5625ac454ec8
:END:
#+title: June-2022

* disdain

I disdain Tik Tok short videos.

I disdain to watch Tik Tok videos.

* strike the eyes

The bad economist sees only what immediately strikes the eye; the good economist also looks beyond.

* spendthrift

don't be a spendthrift, or you will go bankrupt

* fallacy

economic fallacies

* dreadful

the service was deadful

* vandalism

This little act of vandalism will in the first instance mean more business for some glazier.

* hoodlum

a young hoodlum

* gaping

a gaping hole

* shattered

shattered glass

* tailor

someone whose job is to repair clothes

* propensity

* dilate

** to make something wider

** to write or speak about somthing for a long time

He likes to dilate upon programming topics

* deter deterrent

The larger the percentage of the national income taken by taxes the greater the deterrent to private production and employment

* debt

something that is owed to someone else

* loan

an amount of money that is borrowed

* favoritism

** unfair support to one person or groupd

they show favoritism toward their younger daughter

* mortgage

mortgage paypment
