:PROPERTIES:
:ID:       9edad270-ebfc-43c8-b52f-0801787b74b6
:END:
#+title: Term
#+filetags: :Cloud-Native:

- tag :: [[id:15116898-24f7-4a6c-8351-e5a3f4e38dca][Cloud Native]]

* Upstream/Downstream


A (-> request) B (-> request) C

C is downstream dependency of B.
B is upsstream dependency of C.

* Scaling

** Vertical scaling
   Adding hardware

** Horizontal scaling
   Adding service instances, for example containers in Kubernetes.

* Resilience

Always assume your server are certain to fail, and give a solution to it.

* Manageable

A system can be considered manageable if it's possible to sufficiently alter its behavior without having to alter its code. (environment vairables, config files, use some apis [you can config caddy2 via http] to alter system's behavior)

** Maintainablility
   how easy it is to change from inside (code).

* State

** Application state
 
  Server-side data about the application or how it's being used by a client. A common example is client session tracking.

** Resource state
   The current state of a resource within a service at any point of time. It's the same for every client, and has nothing to do with the interation between client and server.
