:PROPERTIES:
:ID:       c1a1d64c-bf59-40bd-8ebe-16659cacb2bf
:END:
#+title: Nietzsche

* focus on real life to solve your problem

* live a meaningful life

to live is to suffer, to survive is to find some meaning in the suffering

life of purpose; life of meaning
find a meaning of your suffering

* follow your own life goals

to forget one's purpose is the commonest form of stupidity

no price is too high for the privilege of owning yourself

do not follow what everyone else if doing

try to find your own path in life

formulate your values and judge every situation through the filter of your own experience and knowledge

** superhuman 

- self-sufficent
- strong
- create their own values

strive for superhuman

work for independence work for goal

if those people cannot like you for who you really are, you will live a life full of lies.

it's much better to live an authentic life, a life in which you can be yourself and live a life you want to live.

* keep your mind open

there are no facts
there are only interpretations

avoid conviction

to live a good life you need to develop yourself and your knowledge and skills

* take care of your body

there is no true unity and order in this universe

only thing we have is our direct experience with this world, through our body

your body always sends message of what it needs

you need to follow the optimal cycle to keep your body healthy

* embrace your evil quality

we should not follow any system

we cannot have a good life if we don't allow ourselves to be ourselves

bring the dark side to the surface

* consume art

without music, life will be a mistake

art is an expression of our freedom. we should exercise our freedom as much as possible

if you can create art, it can help you express yourself freely, and thus you will understand you emotions and feelings better.

* cultivate friendship especially on romantic

friendship is the highest form of love

do not marry for love
marry someone you like talking to

in the long run, what matters is not the passion. but the way we connect with each other.

* be patient with your self-growth

it's important to become a master of ourselves

