:PROPERTIES:
:ID:       97b00dbd-99b4-46ab-91f9-fc8a92ecb0d6
:END:
#+title: Feb-2023

* abstain

** to decided not to use your vote

I abstained in the vote.

** not do

I decided to abstain from pornography.

* stem from (based on)

most of your thinking stems from your past experience.

* sleep in

I used to sleep in because there is nothing I like waking up for.

* fluctuation

If there is a fluctuation in the market there exist opportunities to make money.

* precedent

She has cheated before. That's a dangerous precedent if you want a mono(monogamy) relationship.

* hectic

I want to be free from hectic work as soon as possible.

* inept

I used to be inept at dealing with intimate relationship.

* exacerbate 

antonym: optimize

Being emotional exacerbated our relationship.

* distributable

"dist" stands for distributable in a programming project.

* battered

My laptop was battered because I used it a log and it was drenched with heavy rain once.

* contagion

The man got AIDS by contagion from unsafe sex.

* aviation

the aviation industry

* exploit

exploit resources/technology/opportunities

* cockpit

I like the picture of Amuro Rei sitting in the Gumdam's cockpit.

* intimidated

I used to be intimidated about talking to strangers.

* spur

The money I make from the stock market is a spur to my investigation of crypto.

* akin

JavaScript is akin to C.

* dissident

A large number of dissidents were arrested after the protest.

* defiance

I'm in defiance of the censorship on the Internet.

* tally

The data published by the government didn't tally with people's expectation.

* vilify

In China, feminism is vilified on social media.

* compelled

When you feel compelled to do things, you are on track.

* battalion

a battalion of soliders.

* an order of magnitude

The amount of energy necessary to refute bullshit is an order of magnitude than to produce it. – Paul Kedrosky

* elusive

"love" is an elusive concept.

* disposition

I'm of a procrastinated disposition.

* serenity

keep serenity in chaos.

I was in serenity at most of the time I spent with Kay

* prudence

* precarious

Save some money in preparation of precarious financial situation.

* demoralize

The past failures demoralzied me.

* ecstatic

I used to feel ecstatic about gaming.

* morale

Morale is gained from your past success.

* crude

To design a complex system, you start with a crude solution then keep optimizing it.

* contempt

* astray

Most people are led astray by education.

* obsolete

jQuery is an obsolete technology.

* cubicle

You can take off your clothes in the cubicle.

* fastidious

He is fastidious about the tidyness of his room.

* dictate

a programming language dictates how you think about programs.

* equanimity


